# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nicholas/Documents/projects/tool_rad

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nicholas/Documents/projects/tool_rad

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cpack --config ./CPackSourceConfig.cmake /home/nicholas/Documents/projects/tool_rad/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\" \"sourcemeta_jsontoolkit\" \"sourcemeta_jsontoolkit_dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.30.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicholas/Documents/projects/tool_rad/CMakeFiles /home/nicholas/Documents/projects/tool_rad//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicholas/Documents/projects/tool_rad/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rad

# Build rule for target.
rad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rad
.PHONY : rad

# fast build rule for target.
rad/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/rad.dir/build.make src/CMakeFiles/rad.dir/build
.PHONY : rad/fast

#=============================================================================
# Target rules for targets named ConfigFile

# Build rule for target.
ConfigFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConfigFile
.PHONY : ConfigFile

# fast build rule for target.
ConfigFile/fast:
	$(MAKE) $(MAKESILENT) -f src/config/CMakeFiles/ConfigFile.dir/build.make src/config/CMakeFiles/ConfigFile.dir/build
.PHONY : ConfigFile/fast

#=============================================================================
# Target rules for targets named ADRs

# Build rule for target.
ADRs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ADRs
.PHONY : ADRs

# fast build rule for target.
ADRs/fast:
	$(MAKE) $(MAKESILENT) -f src/adrs/CMakeFiles/ADRs.dir/build.make src/adrs/CMakeFiles/ADRs.dir/build
.PHONY : ADRs/fast

#=============================================================================
# Target rules for targets named Markdown

# Build rule for target.
Markdown: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Markdown
.PHONY : Markdown

# fast build rule for target.
Markdown/fast:
	$(MAKE) $(MAKESILENT) -f src/markdown/CMakeFiles/Markdown.dir/build.make src/markdown/CMakeFiles/Markdown.dir/build
.PHONY : Markdown/fast

#=============================================================================
# Target rules for targets named test_ConfigFile

# Build rule for target.
test_ConfigFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ConfigFile
.PHONY : test_ConfigFile

# fast build rule for target.
test_ConfigFile/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ConfigFile.dir/build.make tests/CMakeFiles/test_ConfigFile.dir/build
.PHONY : test_ConfigFile/fast

#=============================================================================
# Target rules for targets named test_Markdown

# Build rule for target.
test_Markdown: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Markdown
.PHONY : test_Markdown

# fast build rule for target.
test_Markdown/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_Markdown.dir/build.make tests/CMakeFiles/test_Markdown.dir/build
.PHONY : test_Markdown/fast

#=============================================================================
# Target rules for targets named test_ADR

# Build rule for target.
test_ADR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ADR
.PHONY : test_ADR

# fast build rule for target.
test_ADR/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ADR.dir/build.make tests/CMakeFiles/test_ADR.dir/build
.PHONY : test_ADR/fast

#=============================================================================
# Target rules for targets named uriparser

# Build rule for target.
uriparser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uriparser
.PHONY : uriparser

# fast build rule for target.
uriparser/fast:
	$(MAKE) $(MAKESILENT) -f _deps/jsontoolkit-build/vendor/uriparser/CMakeFiles/uriparser.dir/build.make _deps/jsontoolkit-build/vendor/uriparser/CMakeFiles/uriparser.dir/build
.PHONY : uriparser/fast

#=============================================================================
# Target rules for targets named sourcemeta_jsontoolkit_uri

# Build rule for target.
sourcemeta_jsontoolkit_uri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_jsontoolkit_uri
.PHONY : sourcemeta_jsontoolkit_uri

# fast build rule for target.
sourcemeta_jsontoolkit_uri/fast:
	$(MAKE) $(MAKESILENT) -f _deps/jsontoolkit-build/src/uri/CMakeFiles/sourcemeta_jsontoolkit_uri.dir/build.make _deps/jsontoolkit-build/src/uri/CMakeFiles/sourcemeta_jsontoolkit_uri.dir/build
.PHONY : sourcemeta_jsontoolkit_uri/fast

#=============================================================================
# Target rules for targets named sourcemeta_jsontoolkit_json

# Build rule for target.
sourcemeta_jsontoolkit_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_jsontoolkit_json
.PHONY : sourcemeta_jsontoolkit_json

# fast build rule for target.
sourcemeta_jsontoolkit_json/fast:
	$(MAKE) $(MAKESILENT) -f _deps/jsontoolkit-build/src/json/CMakeFiles/sourcemeta_jsontoolkit_json.dir/build.make _deps/jsontoolkit-build/src/json/CMakeFiles/sourcemeta_jsontoolkit_json.dir/build
.PHONY : sourcemeta_jsontoolkit_json/fast

#=============================================================================
# Target rules for targets named sourcemeta_jsontoolkit_jsonpointer

# Build rule for target.
sourcemeta_jsontoolkit_jsonpointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_jsontoolkit_jsonpointer
.PHONY : sourcemeta_jsontoolkit_jsonpointer

# fast build rule for target.
sourcemeta_jsontoolkit_jsonpointer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/jsontoolkit-build/src/jsonpointer/CMakeFiles/sourcemeta_jsontoolkit_jsonpointer.dir/build.make _deps/jsontoolkit-build/src/jsonpointer/CMakeFiles/sourcemeta_jsontoolkit_jsonpointer.dir/build
.PHONY : sourcemeta_jsontoolkit_jsonpointer/fast

#=============================================================================
# Target rules for targets named sourcemeta_jsontoolkit_jsonschema

# Build rule for target.
sourcemeta_jsontoolkit_jsonschema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_jsontoolkit_jsonschema
.PHONY : sourcemeta_jsontoolkit_jsonschema

# fast build rule for target.
sourcemeta_jsontoolkit_jsonschema/fast:
	$(MAKE) $(MAKESILENT) -f _deps/jsontoolkit-build/src/jsonschema/CMakeFiles/sourcemeta_jsontoolkit_jsonschema.dir/build.make _deps/jsontoolkit-build/src/jsonschema/CMakeFiles/sourcemeta_jsontoolkit_jsonschema.dir/build
.PHONY : sourcemeta_jsontoolkit_jsonschema/fast

#=============================================================================
# Target rules for targets named sourcemeta_jsontoolkit_jsonl

# Build rule for target.
sourcemeta_jsontoolkit_jsonl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sourcemeta_jsontoolkit_jsonl
.PHONY : sourcemeta_jsontoolkit_jsonl

# fast build rule for target.
sourcemeta_jsontoolkit_jsonl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/jsontoolkit-build/src/jsonl/CMakeFiles/sourcemeta_jsontoolkit_jsonl.dir/build.make _deps/jsontoolkit-build/src/jsonl/CMakeFiles/sourcemeta_jsontoolkit_jsonl.dir/build
.PHONY : sourcemeta_jsontoolkit_jsonl/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named CLI11

# Build rule for target.
CLI11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLI11
.PHONY : CLI11

# fast build rule for target.
CLI11/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cli11_proj-build/src/CMakeFiles/CLI11.dir/build.make _deps/cli11_proj-build/src/CMakeFiles/CLI11.dir/build
.PHONY : CLI11/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/fmt-build/CMakeFiles/fmt.dir/build.make _deps/fmt-build/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... ADRs"
	@echo "... CLI11"
	@echo "... ConfigFile"
	@echo "... Markdown"
	@echo "... fmt"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... rad"
	@echo "... sourcemeta_jsontoolkit_json"
	@echo "... sourcemeta_jsontoolkit_jsonl"
	@echo "... sourcemeta_jsontoolkit_jsonpointer"
	@echo "... sourcemeta_jsontoolkit_jsonschema"
	@echo "... sourcemeta_jsontoolkit_uri"
	@echo "... test_ADR"
	@echo "... test_ConfigFile"
	@echo "... test_Markdown"
	@echo "... uriparser"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
